### ISSUE TITLE
Leaving the scoring app

### ISSUE THREAD

**Issue by thefallen127** [orange-alliance/project-ems#9]
If you leave the scoring app mid match it will return on match not selected.

**Comment by kyle-flynn** [comment]
This is actually really complicated to setup. I'm not sure it's worth the time to fix. In previous years if EMS crashed we would consider it a field fault, and give the teams a replay of the match. We haven't had any issues with this, and we will tell scorekeepers to not leave the scoring page while a match is running.

Actually I can easily add a notification for this.

**Comment by kyle-flynn** [comment]
Closing for now
